-- Arte no Croche - setup completo para Supabase
-- Rode este arquivo no Supabase Dashboard > SQL Editor.
-- Admin criado:
--   usuario/nome: maou
--   email: maou@gmail.com
--   senha: 123456

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  avatar text default '/avatars/default.jpg',
  role text not null default 'Cliente',
  role_color text not null default '#9c8378',
  permissions text[] not null default '{}',
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'Administrador'
  );
$$;

create table if not exists public.products (
  id integer primary key,
  name text not null,
  price numeric not null default 0,
  image text not null default '',
  images text[] not null default '{}',
  category text not null default 'tapecarias',
  subcategory text,
  style text[] not null default '{}',
  color text[] not null default '{}',
  is_new boolean not null default true,
  is_bestseller boolean not null default false,
  discount_percent numeric not null default 0,
  rating numeric not null default 0,
  rating_count integer not null default 0,
  collection_id integer,
  sell_individually boolean not null default true,
  description text not null default '',
  in_game_images text[] not null default '{}',
  specs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text not null default '',
  image text not null default '',
  color text not null default '#df745c',
  price numeric not null default 0,
  discount_percent numeric not null default 0,
  active boolean not null default true,
  product_ids integer[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.product_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_styles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_colors (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  hex text not null default '#df745c',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.feedbacks (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  discord text,
  rating integer not null default 5 check (rating between 1 and 5),
  text text not null,
  approved boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.help_topics (
  id text primary key,
  title text not null,
  answer text not null,
  sort_order integer not null default 1,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  discount numeric not null default 0,
  type text not null default 'percent' check (type in ('percent', 'fixed')),
  min_purchase numeric,
  max_uses integer,
  uses integer not null default 0,
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_email text not null,
  customer_discord text,
  customer_avatar text default '/avatars/default.jpg',
  status text not null default 'em_processamento' check (status in ('concluido', 'em_processamento', 'pago', 'cancelado')),
  total numeric not null default 0,
  items jsonb not null default '[]'::jsonb,
  coupon_code text,
  discount_amount numeric not null default 0,
  payment_method text not null default 'whatsapp',
  payment_status text not null default 'pendente' check (payment_status in ('pendente', 'pago')),
  discord_verified boolean not null default false,
  payment_proof_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.banners (
  id uuid primary key default gen_random_uuid(),
  title text not null default '',
  image text not null,
  link text not null default '',
  position text not null default 'home' check (position in ('home', 'loja', 'colecoes')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  color text not null default '#df745c',
  permissions text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  avatar text default '/avatars/default.jpg',
  discord text,
  total_orders integer not null default 0,
  total_spent numeric not null default 0,
  status text not null default 'ativo' check (status in ('ativo', 'inativo')),
  created_at timestamptz not null default now()
);

create table if not exists public.product_ratings (
  product_id integer not null references public.products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (product_id, user_id)
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.collections enable row level security;
alter table public.product_categories enable row level security;
alter table public.product_styles enable row level security;
alter table public.product_colors enable row level security;
alter table public.feedbacks enable row level security;
alter table public.site_settings enable row level security;
alter table public.help_topics enable row level security;
alter table public.coupons enable row level security;
alter table public.orders enable row level security;
alter table public.banners enable row level security;
alter table public.roles enable row level security;
alter table public.customers enable row level security;
alter table public.product_ratings enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_admin());

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles
  for insert to authenticated
  with check (id = auth.uid());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles
  for update to authenticated
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products" on public.products
  for select using (true);

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products" on public.products
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read active collections" on public.collections;
create policy "Public can read active collections" on public.collections
  for select using (active = true or public.is_admin());

drop policy if exists "Admins can manage collections" on public.collections;
create policy "Admins can manage collections" on public.collections
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read categories" on public.product_categories;
create policy "Public can read categories" on public.product_categories
  for select using (active = true or public.is_admin());

drop policy if exists "Admins can manage categories" on public.product_categories;
create policy "Admins can manage categories" on public.product_categories
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read styles" on public.product_styles;
create policy "Public can read styles" on public.product_styles
  for select using (active = true or public.is_admin());

drop policy if exists "Admins can manage styles" on public.product_styles;
create policy "Admins can manage styles" on public.product_styles
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read colors" on public.product_colors;
create policy "Public can read colors" on public.product_colors
  for select using (active = true or public.is_admin());

drop policy if exists "Admins can manage colors" on public.product_colors;
create policy "Admins can manage colors" on public.product_colors
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Feedbacks public read approved" on public.feedbacks;
create policy "Feedbacks public read approved" on public.feedbacks
  for select using (approved = true or public.is_admin());

drop policy if exists "Feedbacks public insert" on public.feedbacks;
create policy "Feedbacks public insert" on public.feedbacks
  for insert with check (rating between 1 and 5 and length(trim(name)) > 0 and length(trim(text)) > 0);

drop policy if exists "Admins can manage feedbacks" on public.feedbacks;
create policy "Admins can manage feedbacks" on public.feedbacks
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings" on public.site_settings
  for select using (true);

drop policy if exists "Admins can manage site settings" on public.site_settings;
create policy "Admins can manage site settings" on public.site_settings
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read help topics" on public.help_topics;
create policy "Public can read help topics" on public.help_topics
  for select using (active = true or public.is_admin());

drop policy if exists "Admins can manage help topics" on public.help_topics;
create policy "Admins can manage help topics" on public.help_topics
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can manage coupons" on public.coupons;
create policy "Admins can manage coupons" on public.coupons
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can manage orders" on public.orders;
create policy "Admins can manage orders" on public.orders
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Public can read active banners" on public.banners;
create policy "Public can read active banners" on public.banners
  for select using (active = true or public.is_admin());

drop policy if exists "Admins can manage banners" on public.banners;
create policy "Admins can manage banners" on public.banners
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can manage roles" on public.roles;
create policy "Admins can manage roles" on public.roles
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can manage customers" on public.customers;
create policy "Admins can manage customers" on public.customers
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Users can read product ratings" on public.product_ratings;
create policy "Users can read product ratings" on public.product_ratings
  for select using (true);

drop policy if exists "Users can insert own product ratings" on public.product_ratings;
create policy "Users can insert own product ratings" on public.product_ratings
  for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own product ratings" on public.product_ratings;
create policy "Users can update own product ratings" on public.product_ratings
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.rate_product(p_product_id integer, p_rating integer)
returns table (rating numeric, rating_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rating numeric;
  v_count integer;
begin
  if auth.uid() is null then
    raise exception 'Usuario precisa estar logado para avaliar.';
  end if;

  if p_rating < 1 or p_rating > 5 then
    raise exception 'A avaliacao precisa ser entre 1 e 5.';
  end if;

  insert into public.product_ratings (product_id, user_id, rating)
  values (p_product_id, auth.uid(), p_rating)
  on conflict (product_id, user_id)
  do update set rating = excluded.rating, updated_at = now();

  select round(avg(pr.rating)::numeric, 1), count(*)::integer
    into v_rating, v_count
  from public.product_ratings pr
  where pr.product_id = p_product_id;

  update public.products
    set rating = coalesce(v_rating, 0),
        rating_count = coalesce(v_count, 0)
  where id = p_product_id;

  return query select coalesce(v_rating, 0), coalesce(v_count, 0);
end;
$$;

grant execute on function public.rate_product(integer, integer) to authenticated;

insert into public.roles (name, color, permissions)
values
  ('Administrador', '#df745c', array['all']),
  ('Cliente', '#9c8378', array[]::text[])
on conflict (name) do update set
  color = excluded.color,
  permissions = excluded.permissions;

insert into public.product_categories (name, slug, active)
values
  ('Tapecarias', 'tapecarias', true),
  ('Quadros', 'quadros', true),
  ('Almofadas', 'almofadas', true),
  ('Acessorios', 'acessorios', true)
on conflict (slug) do update set name = excluded.name, active = excluded.active;

insert into public.product_styles (name, slug, active)
values
  ('Boho', 'boho', true),
  ('Minimalista', 'minimalista', true),
  ('Botanico', 'botanico', true),
  ('Organico', 'organico', true),
  ('Afetivo', 'afetivo', true)
on conflict (slug) do update set name = excluded.name, active = excluded.active;

insert into public.product_colors (name, slug, hex, active)
values
  ('Cru', 'cru', '#f7eadc', true),
  ('Terracota', 'terracota', '#c96c55', true),
  ('Rose', 'rose', '#e6a394', true),
  ('Verde', 'verde', '#75815f', true),
  ('Madeira', 'madeira', '#a8754b', true),
  ('Dourado', 'dourado', '#c89754', true)
on conflict (slug) do update set name = excluded.name, hex = excluded.hex, active = excluded.active;

insert into public.collections (id, name, subtitle, image, color, price, discount_percent, active, product_ids, created_at)
overriding system value
values
  (1, 'Tapecarias Autorais', 'Pecas de parede feitas a mao para dar alma ao ambiente.', '/crochet/foto_2.jpeg', '#df745c', 299.90, 0, true, array[1,2,8,11], '2026-05-01T10:00:00.000Z'),
  (2, 'Tons da Terra', 'Texturas em cru, rose, verde e terracota para uma casa acolhedora.', '/crochet/foto_5.jpeg', '#9f7e56', 329.90, 0, true, array[3,4,10,12], '2026-05-02T10:00:00.000Z'),
  (3, 'Afetos da Casa', 'Quadros, almofadas e detalhes para presentear ou morar melhor.', '/crochet/foto_7.jpeg', '#75815f', 159.90, 0, true, array[5,6,7,9], '2026-05-03T10:00:00.000Z')
on conflict (id) do update set
  name = excluded.name,
  subtitle = excluded.subtitle,
  image = excluded.image,
  color = excluded.color,
  price = excluded.price,
  discount_percent = excluded.discount_percent,
  active = excluded.active,
  product_ids = excluded.product_ids;

select setval(pg_get_serial_sequence('public.collections', 'id'), greatest((select max(id) from public.collections), 1), true);

insert into public.products (
  id, name, price, image, images, category, style, color, is_new, is_bestseller,
  discount_percent, rating, rating_count, collection_id, sell_individually, description, specs, created_at
)
values
  (1, 'Folhagem Encanto', 349.90, '/crochet/foto_2.jpeg', array['/crochet/foto_2.jpeg','/crochet/foto_3.jpeg'], 'tapecarias', array['botanico','boho'], array['cru','verde','terracota'], true, true, 0, 5, 18, 1, true, 'Tapecaria artesanal em croche com desenho botanico, feita para transformar paredes com delicadeza.', '[{"label":"Material","value":"Fio de algodao"},{"label":"Producao","value":"Feita a mao"},{"label":"Entrega","value":"Lorena e regiao"}]'::jsonb, '2026-05-01T10:00:00.000Z'),
  (2, 'Fases da Lua', 299.90, '/crochet/foto_3.jpeg', array['/crochet/foto_3.jpeg','/crochet/foto_4.jpeg'], 'tapecarias', array['minimalista','boho'], array['cru','dourado'], true, true, 0, 5, 12, 1, true, 'Peca de parede com acabamento manual para um ambiente calmo, acolhedor e cheio de personalidade.', '[{"label":"Material","value":"Algodao natural"},{"label":"Prazo","value":"Sob encomenda"},{"label":"Atendimento","value":"Pelo WhatsApp"}]'::jsonb, '2026-05-02T10:00:00.000Z'),
  (3, 'Formas Organicas', 349.90, '/crochet/foto_4.jpeg', array['/crochet/foto_4.jpeg','/crochet/foto_5.jpeg'], 'tapecarias', array['organico','afetivo'], array['cru','rose','verde'], true, true, 0, 5, 21, 2, true, 'Tapecaria em tons suaves, pensada para quartos, salas e espacos de descanso.', '[{"label":"Material","value":"Algodao premium"},{"label":"Cuidados","value":"Limpeza delicada"},{"label":"Producao","value":"Manual"}]'::jsonb, '2026-05-03T10:00:00.000Z'),
  (4, 'Sol Nascente', 329.90, '/crochet/foto_5.jpeg', array['/crochet/foto_5.jpeg','/crochet/foto_6.jpeg'], 'tapecarias', array['boho','minimalista'], array['cru','terracota'], true, false, 0, 5, 9, 2, true, 'Peca com visual solar e textura aconchegante para trazer calor visual ao ambiente.', '[{"label":"Material","value":"Fio de algodao"},{"label":"Instalacao","value":"Pronta para pendurar"},{"label":"Entrega","value":"Entrega local"}]'::jsonb, '2026-05-04T10:00:00.000Z'),
  (5, 'Vaso de Afeto', 249.90, '/crochet/foto_6.jpeg', array['/crochet/foto_6.jpeg','/crochet/foto_7.jpeg'], 'quadros', array['botanico','afetivo'], array['cru','verde','terracota'], false, true, 0, 5, 16, 3, true, 'Quadro em croche com toque afetivo para decorar com leveza e carinho.', '[{"label":"Material","value":"Algodao e bastidor"},{"label":"Acabamento","value":"Artesanal"},{"label":"Entrega","value":"Local personalizada"}]'::jsonb, now()),
  (6, 'Almofada Jardim', 159.90, '/crochet/foto_7.jpeg', array['/crochet/foto_7.jpeg','/crochet/foto_8.jpeg'], 'almofadas', array['botanico','boho'], array['cru','verde'], true, false, 0, 5, 7, 3, true, 'Almofada de croche com textura alta e toque artesanal para sofa, cama ou poltrona.', '[{"label":"Material","value":"Capa em algodao"},{"label":"Enchimento","value":"Macio e confortavel"},{"label":"Producao","value":"Feita a mao"}]'::jsonb, now()),
  (7, 'Trama Aconchego', 189.90, '/crochet/foto_8.jpeg', array['/crochet/foto_8.jpeg'], 'almofadas', array['minimalista','afetivo'], array['cru','rose'], true, true, 0, 5, 11, 3, true, 'Peca macia e decorativa para completar cantinhos de descanso com textura artesanal.', '[{"label":"Material","value":"Fio macio"},{"label":"Uso","value":"Decorativo"},{"label":"Atendimento","value":"Pelo WhatsApp"}]'::jsonb, now()),
  (8, 'Jardim Suspenso', 279.90, '/crochet/foto_9.jpeg', array['/crochet/foto_9.jpeg'], 'tapecarias', array['botanico','organico'], array['verde','cru','madeira'], false, true, 0, 5, 14, 1, true, 'Decoracao de parede com inspiracao botanica para deixar o ambiente mais vivo.', '[{"label":"Material","value":"Algodao"},{"label":"Acabamento","value":"Com detalhes manuais"},{"label":"Entrega","value":"Lorena e regiao"}]'::jsonb, now()),
  (9, 'Lares de Algodao', 219.90, '/crochet/foto_10.jpeg', array['/crochet/foto_10.jpeg'], 'acessorios', array['boho','afetivo'], array['cru','madeira'], true, false, 0, 5, 6, 3, true, 'Detalhe artesanal para compor mesas, aparadores e cantinhos especiais da casa.', '[{"label":"Material","value":"Algodao"},{"label":"Uso","value":"Decoracao"},{"label":"Producao","value":"Manual"}]'::jsonb, now()),
  (10, 'Flor de Parede', 269.90, '/crochet/foto_11.jpeg', array['/crochet/foto_11.jpeg'], 'quadros', array['botanico','boho'], array['cru','rose','verde'], true, true, 0, 5, 13, 2, true, 'Quadro/tapecaria floral para trazer delicadeza e textura para a parede.', '[{"label":"Material","value":"Fio de algodao"},{"label":"Acabamento","value":"Artesanal"},{"label":"Atendimento","value":"Pelo WhatsApp"}]'::jsonb, now()),
  (11, 'Canto Sereno', 199.90, '/crochet/foto_12.jpeg', array['/crochet/foto_12.jpeg'], 'acessorios', array['minimalista','organico'], array['cru','dourado'], false, false, 0, 5, 5, 1, true, 'Peca artesanal pequena para dar charme a detalhes do ambiente.', '[{"label":"Material","value":"Algodao"},{"label":"Uso","value":"Decorativo"},{"label":"Entrega","value":"Local"}]'::jsonb, now()),
  (12, 'Textura do Lar', 239.90, '/crochet/foto_13.jpeg', array['/crochet/foto_13.jpeg'], 'tapecarias', array['afetivo','boho'], array['cru','terracota'], true, false, 0, 5, 8, 2, true, 'Tapecaria artesanal para deixar a casa mais acolhedora e com identidade propria.', '[{"label":"Material","value":"Fio artesanal"},{"label":"Producao","value":"Feita a mao"},{"label":"Entrega","value":"Lorena e regiao"}]'::jsonb, now())
on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  image = excluded.image,
  images = excluded.images,
  category = excluded.category,
  style = excluded.style,
  color = excluded.color,
  is_new = excluded.is_new,
  is_bestseller = excluded.is_bestseller,
  discount_percent = excluded.discount_percent,
  rating = excluded.rating,
  rating_count = excluded.rating_count,
  collection_id = excluded.collection_id,
  sell_individually = excluded.sell_individually,
  description = excluded.description,
  specs = excluded.specs,
  created_at = excluded.created_at;

insert into public.help_topics (id, title, answer, sort_order, active)
values
  ('faq', 'Perguntas Frequentes', 'Aqui voce encontra respostas para as principais duvidas sobre produtos, entrega local e atendimento.', 1, true),
  ('como-comprar', 'Como comprar', 'Escolha a peca desejada e clique em comprar pelo WhatsApp. O atendimento, combinados de entrega e pagamento acontecem por la.', 2, true),
  ('trocas-devolucoes', 'Trocas e Devolucoes', 'Como as pecas sao artesanais, trocas e ajustes sao avaliados pelo atendimento de acordo com cada caso.', 3, true),
  ('fale-conosco', 'Fale Conosco', 'O atendimento acontece pelo WhatsApp oficial da loja. Chame a gente para tirar duvidas, combinar entrega e fazer seu pedido.', 4, true)
on conflict (id) do update set
  title = excluded.title,
  answer = excluded.answer,
  sort_order = excluded.sort_order,
  active = excluded.active,
  updated_at = now();

insert into public.site_settings (key, value)
values
  ('whatsapp_number', '5512991234567'),
  ('whatsapp_message', 'Ola! Vim pelo site Arte no Croche e quero fazer um pedido.')
on conflict (key) do update set value = excluded.value, updated_at = now();

insert into public.feedbacks (name, email, rating, text, approved)
values
  ('Juliana M.', 'juliana@example.com', 5, 'Simplesmente apaixonada. A peca e ainda mais linda pessoalmente e transformou meu ambiente.', true),
  ('Camila R.', 'camila@example.com', 5, 'Pecas unicas, feitas com muito carinho e capricho. Chegou rapido e veio tudo perfeito.', true),
  ('Fernanda L.', 'fernanda@example.com', 5, 'A tapecaria deixou minha sala linda e super aconchegante. Da para sentir o amor em cada detalhe.', true)
on conflict do nothing;

do $$
declare
  v_admin_id uuid;
begin
  select id into v_admin_id
  from auth.users
  where lower(email) = 'maou@gmail.com'
  limit 1;

  if v_admin_id is null then
    v_admin_id := gen_random_uuid();

    insert into auth.users (
      instance_id,
      id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      invited_at,
      confirmation_token,
      confirmation_sent_at,
      recovery_token,
      recovery_sent_at,
      email_change_token_new,
      email_change,
      email_change_sent_at,
      last_sign_in_at,
      raw_app_meta_data,
      raw_user_meta_data,
      is_super_admin,
      created_at,
      updated_at,
      phone,
      phone_confirmed_at,
      phone_change,
      phone_change_token,
      phone_change_sent_at,
      email_change_token_current,
      email_change_confirm_status,
      banned_until,
      reauthentication_token,
      reauthentication_sent_at,
      is_sso_user,
      deleted_at
    )
    values (
      '00000000-0000-0000-0000-000000000000',
      v_admin_id::text,
      'authenticated',
      'authenticated',
      'maou@gmail.com',
      crypt('123456', gen_salt('bf')),
      now(),
      null,
      '',
      null,
      '',
      null,
      '',
      '',
      null,
      null,
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"name":"maou"}'::jsonb,
      false,
      now(),
      now(),
      null,
      null,
      '',
      '',
      null,
      '',
      0,
      null,
      '',
      null,
      false,
      null
    );

    insert into auth.identities (
      id,
      user_id,
      identity_data,
      provider,
      provider_id,
      last_sign_in_at,
      created_at,
      updated_at
    )
    values (
      v_admin_id,
      v_admin_id,
      jsonb_build_object('sub', v_admin_id::text, 'email', 'maou@gmail.com', 'email_verified', true, 'name', 'maou'),
      'email',
      'maou@gmail.com',
      now(),
      now(),
      now()
    )
    on conflict (provider, provider_id) do nothing;
  else
    update auth.users
    set encrypted_password = crypt('123456', gen_salt('bf')),
        email_confirmed_at = coalesce(email_confirmed_at, now()),
        raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb) || '{"name":"maou"}'::jsonb,
        updated_at = now()
    where id = v_admin_id;
  end if;

  insert into public.profiles (id, name, email, avatar, role, role_color, permissions)
  values (
    v_admin_id,
    'maou',
    'maou@gmail.com',
    '/avatars/default.jpg',
    'Administrador',
    '#df745c',
    array['all']
  )
  on conflict (id) do update set
    name = excluded.name,
    email = excluded.email,
    avatar = excluded.avatar,
    role = excluded.role,
    role_color = excluded.role_color,
    permissions = excluded.permissions;
end $$;

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read uploaded images" on storage.objects;
create policy "Public can read uploaded images"
  on storage.objects for select
  using (bucket_id = 'images');

drop policy if exists "Admins can upload images" on storage.objects;
create policy "Admins can upload images"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'images' and public.is_admin());

drop policy if exists "Admins can update images" on storage.objects;
create policy "Admins can update images"
  on storage.objects for update to authenticated
  using (bucket_id = 'images' and public.is_admin())
  with check (bucket_id = 'images' and public.is_admin());

drop policy if exists "Admins can delete images" on storage.objects;
create policy "Admins can delete images"
  on storage.objects for delete to authenticated
  using (bucket_id = 'images' and public.is_admin());
